### ISSUE TITLE
Fail to reproduce results

### ISSUE THREAD

**Issue by MateusZitelli** [vicariousinc/science_rcn#3]
The experiments fails to achieve the announced accuracy:

```sh
python science_rcn/run.py --train_size 100 --test_size 20 --parallel
INFO:__main__:Training on 10 images...
INFO:__main__:Testing on 20 images...
Total test accuracy = 0.1
```

**Comment by tedivm** [comment]
Can you pull down a fresh clone and try this again, showing us the whole terminal session? The command you are running doesn't match the output- the training size is 100 in the command but is only 10 in the output itself (that being said even with  `train_size=10` we are getting an accuracy of `0.55`).

**Comment by MateusZitelli** [comment]
Cloning and running the example again solved the issue, sorry for the false alarm.
